// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalBlogPracticeWebsite.Data.Users;

#nullable disable

namespace PersonalBlogPracticeWebsite.Migrations.UsersDb
{
    [DbContext(typeof(UsersDbContext))]
    [Migration("20220429185542_ChangeConfigForUsers")]
    partial class ChangeConfigForUsers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");
#pragma warning restore 612, 618
        }
    }
}
